In [2]:
import numpy as np
import pandas as pd
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_columns = 20
pd.options.display.max_rows = 20
pd.options.display.max_colwidth = 80
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc("figure", figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

In [3]:
import numpy as np
import pandas as pd

In [18]:
df = pd.DataFrame({"key1" : ["a", "a", None, "b", "b", "a", None],
                   "key2" : pd.Series([1, 2, 1, 2, 1, None, 1],
                                      dtype="Int64"),
                   "data1" : np.random.standard_normal(7),
                   "data2" : np.random.standard_normal(7)})
df

  key1  key2     data1     data2
0    a     1 -1.020903 -0.577385
1    a     2 -1.413416 -1.168634
2  NaN     1  1.296608 -0.825020
3    b     2  0.252275 -2.644409
4    b     1  1.127481 -0.152986
5    a  <NA> -0.568363 -0.751921
6  NaN     1  0.309362 -0.132609

In [21]:
grouped = df["data1"].groupby(df["key1"])
grouped

In [24]:
grouped.mean()

key1
a   -1.000894
b    0.689878
Name: data1, dtype: float64

In [25]:
means = df["data1"].groupby([df["key1"], df["key2"]]).mean()
means

key1  key2
a     1      -1.020903
      2      -1.413416
b     1       1.127481
      2       0.252275
Name: data1, dtype: float64

In [26]:
means.unstack()

key2         1         2
key1
a    -1.020903 -1.413416
b     1.127481  0.252275

In [27]:
states = np.array(["OH", "CA", "CA", "OH", "OH", "CA", "OH"])
years = [2005, 2005, 2006, 2005, 2006, 2005, 2006]
df["data1"].groupby([states, years]).mean()

CA  2005   -0.990890
    2006    1.296608
OH  2005   -0.384314
    2006    0.718422
Name: data1, dtype: float64

In [28]:
df.groupby("key1").mean()
df.groupby("key2").mean(numeric_only=True)
df.groupby(["key1", "key2"]).mean()

              data1     data2
key1 key2
a    1    -1.020903 -0.577385
     2    -1.413416 -1.168634
b    1     1.127481 -0.152986
     2     0.252275 -2.644409

In [29]:
df.groupby(["key1", "key2"]).size()

key1  key2
a     1       1
      2       1
b     1       1
      2       1
dtype: int64

In [30]:
df.groupby("key1", dropna=False).size()
df.groupby(["key1", "key2"], dropna=False).size()

key1  key2
a     1       1
      2       1
      <NA>    1
b     1       1
      2       1
NaN   1       2
dtype: int64

In [31]:
df.groupby("key1").count()

      key2  data1  data2
key1
a        2      3      3
b        2      2      2

In [32]:
for name, group in df.groupby("key1"):
    print(name)
    print(group)

a
  key1  key2     data1     data2
0    a     1 -1.020903 -0.577385
1    a     2 -1.413416 -1.168634
5    a  <NA> -0.568363 -0.751921
b
  key1  key2     data1     data2
3    b     2  0.252275 -2.644409
4    b     1  1.127481 -0.152986

In [33]:
for (k1, k2), group in df.groupby(["key1", "key2"]):
    print((k1, k2))
    print(group)

('a', 1)
  key1  key2     data1     data2
0    a     1 -1.020903 -0.577385
('a', 2)
  key1  key2     data1     data2
1    a     2 -1.413416 -1.168634
('b', 1)
  key1  key2     data1     data2
4    b     1  1.127481 -0.152986
('b', 2)
  key1  key2     data1     data2
3    b     2  0.252275 -2.644409

In [34]:
pieces = {name: group for name, group in df.groupby("key1")}
pieces["b"]

  key1  key2     data1     data2
3    b     2  0.252275 -2.644409
4    b     1  1.127481 -0.152986

In [35]:
grouped = df.groupby({"key1": "key", "key2": "key",
                      "data1": "data", "data2": "data"}, axis="columns")

TypeError: DataFrame.groupby() got an unexpected keyword argument 'axis'

In [37]:
for group_key, group_values in grouped:
    print(group_key)
    print(group_values)

a
0   -1.020903
1   -1.413416
5   -0.568363
Name: data1, dtype: float64
b
3    0.252275
4    1.127481
Name: data1, dtype: float64

In [38]:
df.groupby(["key1", "key2"])[["data2"]].mean()

              data2
key1 key2
a    1    -0.577385
     2    -1.168634
b    1    -0.152986
     2    -2.644409

In [39]:
s_grouped = df.groupby(["key1", "key2"])["data2"]
s_grouped
s_grouped.mean()

key1  key2
a     1      -0.577385
      2      -1.168634
b     1      -0.152986
      2      -2.644409
Name: data2, dtype: float64

In [40]:
people = pd.DataFrame(np.random.standard_normal((5, 5)),
                      columns=["a", "b", "c", "d", "e"],
                      index=["Joe", "Steve", "Wanda", "Jill", "Trey"])
people.iloc[2:3, [1, 2]] = np.nan # Add a few NA values
people

              a         b         c         d         e
Joe    1.457300  0.609512 -0.493779  1.239980 -0.135722
Steve  1.430042 -0.846852  0.603282  1.263572 -0.255491
Wanda -0.445688       NaN       NaN -1.824505  0.625428
Jill   1.022872  1.107425  0.090937 -0.350109  0.217957
Trey  -0.894813 -1.741494 -1.052256  1.436603 -0.576207

In [41]:
mapping = {"a": "red", "b": "red", "c": "blue",
           "d": "blue", "e": "red", "f" : "orange"}

In [42]:
by_column = people.groupby(mapping, axis="columns")
by_column.sum()

TypeError: DataFrame.groupby() got an unexpected keyword argument 'axis'

In [43]:
map_series = pd.Series(mapping)
map_series
people.groupby(map_series, axis="columns").count()

TypeError: DataFrame.groupby() got an unexpected keyword argument 'axis'

In [44]:
people.groupby(len).sum()

          a         b         c         d         e
3  1.457300  0.609512 -0.493779  1.239980 -0.135722
4  0.128059 -0.634069 -0.961319  1.086494 -0.358250
5  0.984353 -0.846852  0.603282 -0.560932  0.369938

In [45]:
key_list = ["one", "one", "one", "two", "two"]
people.groupby([len, key_list]).min()

              a         b         c         d         e
3 one  1.457300  0.609512 -0.493779  1.239980 -0.135722
4 two -0.894813 -1.741494 -1.052256 -0.350109 -0.576207
5 one -0.445688 -0.846852  0.603282 -1.824505 -0.255491

In [46]:
columns = pd.MultiIndex.from_arrays([["US", "US", "US", "JP", "JP"],
                                    [1, 3, 5, 1, 3]],
                                    names=["cty", "tenor"])
hier_df = pd.DataFrame(np.random.standard_normal((4, 5)), columns=columns)
hier_df

cty          US                            JP
tenor         1         3         5         1         3
0     -2.420294 -1.062330  0.237372  0.000957  0.065253
1     -1.367524 -0.030280  0.940489 -0.642437  1.040179
2     -1.082922  0.429214 -0.236224  0.641818 -0.331661
3      1.394072 -1.076742 -0.192466 -0.871188  0.420852

In [47]:
hier_df.groupby(level="cty", axis="columns").count()

TypeError: DataFrame.groupby() got an unexpected keyword argument 'axis'

In [52]:
df
grouped = df.groupby("key1")
grouped["data1"].nsmallest(2)

key1
a     1   -1.413416
      0   -1.020903
b     3    0.252275
      4    1.127481
Name: data1, dtype: float64

In [53]:
def peak_to_peak(arr):
    return arr.max() - arr.min()
grouped.agg(peak_to_peak)

      key2     data1     data2
key1
a        1  0.845053  0.591249
b        1  0.875206  2.491424

In [54]:
grouped.describe()

      key2                                           data1            ...  \
     count mean       std  min   25%  50%   75%  max count      mean  ...
key1                                                                  ...
a      2.0  1.5  0.707107  1.0  1.25  1.5  1.75  2.0   3.0 -1.000894  ...
b      2.0  1.5  0.707107  1.0  1.25  1.5  1.75  2.0   2.0  0.689878  ...

                         data2                                          \
           75%       max count      mean       std       min       25%
key1
a    -0.794633 -0.568363   3.0 -0.832647  0.303778 -1.168634 -0.960278
b     0.908680  1.127481   2.0 -1.398698  1.761703 -2.644409 -2.021554


           50%       75%       max
key1
a    -0.751921 -0.664653 -0.577385
b    -1.398698 -0.775842 -0.152986

[2 rows x 24 columns]

In [55]:
tips = pd.read_csv("examples/tips.csv")
tips.head()

   rachunek  napiwek palacz   dzień     pora  wielkość
0     16.99     1.01    nie  niedz.  kolacja         2
1     10.34     1.66    nie  niedz.  kolacja         3
2     21.01     3.50    nie  niedz.  kolacja         3
3     23.68     3.31    nie  niedz.  kolacja         2
4     24.59     3.61    nie  niedz.  kolacja         4

In [59]:
tips["napiwek_proc"] = tips["napiwek"] / tips["rachunek"]
tips.head()

   rachunek  napiwek palacz   dzień     pora  wielkość  napiwek_proc
0     16.99     1.01    nie  niedz.  kolacja         2      0.059447
1     10.34     1.66    nie  niedz.  kolacja         3      0.160542
2     21.01     3.50    nie  niedz.  kolacja         3      0.166587
3     23.68     3.31    nie  niedz.  kolacja         2      0.139780
4     24.59     3.61    nie  niedz.  kolacja         4      0.146808

In [61]:
grouped = tips.groupby(["dzień", "palacz"])

In [62]:
grouped_pct = grouped["napiwek_proc"]
grouped_pct.agg("mean")

dzień   palacz
czw.    nie       0.160298
        tak       0.163863
niedz.  nie       0.160113
        tak       0.187250
pt.     nie       0.151650
        tak       0.174783
sob.    nie       0.158048
        tak       0.147906
Name: napiwek_proc, dtype: float64

In [63]:
grouped_pct.agg(["mean", "std", peak_to_peak])

                   mean       std  peak_to_peak
dzień  palacz
czw.   nie     0.160298  0.038774      0.193350
       tak     0.163863  0.039389      0.151240
niedz. nie     0.160113  0.042347      0.193226
       tak     0.187250  0.154134      0.644685
pt.    nie     0.151650  0.028123      0.067349
       tak     0.174783  0.051293      0.159925
sob.   nie     0.158048  0.039767      0.235193
       tak     0.147906  0.061375      0.290095

In [64]:
grouped_pct.agg([("average", "mean"), ("stdev", np.std)])

                average     stdev
dzień  palacz
czw.   nie     0.160298  0.038341
       tak     0.163863  0.038213
niedz. nie     0.160113  0.041974
       tak     0.187250  0.150023
pt.    nie     0.151650  0.024355
       tak     0.174783  0.049553
sob.   nie     0.158048  0.039323
       tak     0.147906  0.060640

In [67]:
functions = ["count", "mean", "max"]
result = grouped[["napiwek_proc", "rachunek"]].agg(functions)
result

              napiwek_proc                     rachunek
                     count      mean       max    count       mean    max
dzień  palacz
czw.   nie              45  0.160298  0.266312       45  17.113111  41.19
       tak              17  0.163863  0.241255       17  19.190588  43.11
niedz. nie              57  0.160113  0.252672       57  20.506667  48.17
       tak              19  0.187250  0.710345       19  24.120000  45.35
pt.    nie               4  0.151650  0.187735        4  18.420000  22.75
       tak              15  0.174783  0.263480       15  16.813333  40.17
sob.   nie              45  0.158048  0.291990       45  19.661778  48.33
       tak              42  0.147906  0.325733       42  21.276667  50.81

In [68]:
result["napiwek_proc"]

               count      mean       max
dzień  palacz
czw.   nie        45  0.160298  0.266312
       tak        17  0.163863  0.241255
niedz. nie        57  0.160113  0.252672
       tak        19  0.187250  0.710345
pt.    nie         4  0.151650  0.187735
       tak        15  0.174783  0.263480
sob.   nie        45  0.158048  0.291990
       tak        42  0.147906  0.325733

In [69]:
ftuples = [("Average", "mean"), ("Variance", np.var)]
grouped[["napiwek_proc", "rachunek"]].agg(ftuples)

              napiwek_proc             rachunek
                   Average  Variance    Average    Variance
dzień  palacz
czw.   nie        0.160298  0.001470  17.113111   58.300079
       tak        0.163863  0.001460  19.190588   65.702135
niedz. nie        0.160113  0.001762  20.506667   64.940331
       tak        0.187250  0.022507  24.120000  103.306779
pt.    nie        0.151650  0.000593  18.420000   19.197250
       tak        0.174783  0.002456  16.813333   77.058276
sob.   nie        0.158048  0.001546  19.661778   78.133210
       tak        0.147906  0.003677  21.276667   98.973546

In [74]:
grouped.agg({"napiwek" : np.max, "wielkość" : "sum"})
grouped.agg({"napiwek_proc" : ["min", "max", "mean", "std"],
             "wielkość" : "sum"})

              napiwek_proc                               wielkość
                       min       max      mean       std      sum
dzień  palacz
czw.   nie        0.072961  0.266312  0.160298  0.038774      112
       tak        0.090014  0.241255  0.163863  0.039389       40
niedz. nie        0.059447  0.252672  0.160113  0.042347      167
       tak        0.065660  0.710345  0.187250  0.154134       49
pt.    nie        0.120385  0.187735  0.151650  0.028123        9
       tak        0.103555  0.263480  0.174783  0.051293       31
sob.   nie        0.056797  0.291990  0.158048  0.039767      115
       tak        0.035638  0.325733  0.147906  0.061375      104

In [76]:
grouped = tips.groupby(["dzień", "palacz"], as_index=False)
grouped.mean(numeric_only=True)

    dzień palacz   rachunek   napiwek  wielkość  napiwek_proc
0    czw.    nie  17.113111  2.673778  2.488889      0.160298
1    czw.    tak  19.190588  3.030000  2.352941      0.163863
2  niedz.    nie  20.506667  3.167895  2.929825      0.160113
3  niedz.    tak  24.120000  3.516842  2.578947      0.187250
4     pt.    nie  18.420000  2.812500  2.250000      0.151650
5     pt.    tak  16.813333  2.714000  2.066667      0.174783
6    sob.    nie  19.661778  3.102889  2.555556      0.158048
7    sob.    tak  21.276667  2.875476  2.476190      0.147906

In [78]:
def top(df, n=5, column="napiwek_proc"):
    return df.sort_values(column, ascending=False)[:n]
top(tips, n=6)

     rachunek  napiwek palacz   dzień     pora  wielkość  napiwek_proc
172      7.25     5.15    tak  niedz.  kolacja         2      0.710345
178      9.60     4.00    tak  niedz.  kolacja         2      0.416667
67       3.07     1.00    tak    sob.  kolacja         1      0.325733
232     11.61     3.39    nie    sob.  kolacja         2      0.291990
183     23.17     6.50    tak  niedz.  kolacja         4      0.280535
109     14.31     4.00    tak    sob.  kolacja         2      0.279525

In [80]:
tips.groupby("palacz").apply(top)

            rachunek  napiwek   dzień     pora  wielkość  napiwek_proc
palacz
nie    232     11.61     3.39    sob.  kolacja         2      0.291990
       149      7.51     2.00    czw.    obiad         2      0.266312
       51      10.29     2.60  niedz.  kolacja         2      0.252672
       185     20.69     5.00  niedz.  kolacja         5      0.241663
       88      24.71     5.85    czw.    obiad         2      0.236746
tak    172      7.25     5.15  niedz.  kolacja         2      0.710345
       178      9.60     4.00  niedz.  kolacja         2      0.416667
       67       3.07     1.00    sob.  kolacja         1      0.325733
       183     23.17     6.50  niedz.  kolacja         4      0.280535
       109     14.31     4.00    sob.  kolacja         2      0.279525

In [83]:
tips.groupby(["palacz", "dzień"]).apply(top, n=1, column="rachunek")

                   rachunek  napiwek     pora  wielkość  napiwek_proc
palacz dzień
nie    czw.   142     41.19     5.00    obiad         5      0.121389
       niedz. 156     48.17     5.00  kolacja         6      0.103799
       pt.    94      22.75     3.25  kolacja         2      0.142857
       sob.   212     48.33     9.00  kolacja         4      0.186220
tak    czw.   197     43.11     5.00    obiad         4      0.115982
       niedz. 182     45.35     3.50  kolacja         3      0.077178
       pt.    95      40.17     4.73  kolacja         4      0.117750
       sob.   170     50.81    10.00  kolacja         3      0.196812

In [86]:
result = tips.groupby("palacz")["napiwek_proc"].describe()
result
result.unstack("palacz")

       palacz
count  nie       151.000000
       tak        93.000000
mean   nie         0.159328
       tak         0.163196
std    nie         0.039910
       tak         0.085119
min    nie         0.056797
       tak         0.035638
25%    nie         0.136906
       tak         0.106771
50%    nie         0.155625
       tak         0.153846
75%    nie         0.185014
       tak         0.195059
max    nie         0.291990
       tak         0.710345
dtype: float64

In [88]:
tips.groupby("palacz", group_keys=False).apply(top)

     rachunek  napiwek   dzień     pora  wielkość  napiwek_proc
232     11.61     3.39    sob.  kolacja         2      0.291990
149      7.51     2.00    czw.    obiad         2      0.266312
51      10.29     2.60  niedz.  kolacja         2      0.252672
185     20.69     5.00  niedz.  kolacja         5      0.241663
88      24.71     5.85    czw.    obiad         2      0.236746
172      7.25     5.15  niedz.  kolacja         2      0.710345
178      9.60     4.00  niedz.  kolacja         2      0.416667
67       3.07     1.00    sob.  kolacja         1      0.325733
183     23.17     6.50  niedz.  kolacja         4      0.280535
109     14.31     4.00    sob.  kolacja         2      0.279525

In [89]:
frame = pd.DataFrame({"data1": np.random.standard_normal(1000),
                      "data2": np.random.standard_normal(1000)})
frame.head()
quartiles = pd.cut(frame["data1"], 4)
quartiles.head(10)

0    (-1.568, 0.264]
1    (-1.568, 0.264]
2    (-1.568, 0.264]
3    (-1.568, 0.264]
4     (0.264, 2.096]
5    (-1.568, 0.264]
6     (0.264, 2.096]
7    (-1.568, 0.264]
8     (0.264, 2.096]
9    (-1.568, 0.264]
Name: data1, dtype: category
Categories (4, interval[float64, right]): [(-3.407, -1.568] < (-1.568, 0.264] < (0.264, 2.096] < (2.096, 3.928]]

In [48]:
def get_stats(group):
    return pd.DataFrame(
        {"min": group.min(), "max": group.max(),
        "count": group.count(), "mean": group.mean()}
    )

grouped = frame.groupby(quartiles)
grouped.apply(get_stats)

In [49]:
grouped.agg(["min", "max", "count", "mean"])

In [50]:
quartiles_samp = pd.qcut(frame["data1"], 4, labels=False)
quartiles_samp.head()
grouped = frame.groupby(quartiles_samp)
grouped.apply(get_stats)

In [51]:
s = pd.Series(np.random.standard_normal(6))
s[::2] = np.nan
s
s.fillna(s.mean())

In [52]:
states = ["Ohio", "New York", "Vermont", "Florida",
          "Oregon", "Nevada", "California", "Idaho"]
group_key = ["East", "East", "East", "East",
             "West", "West", "West", "West"]
data = pd.Series(np.random.standard_normal(8), index=states)
data

In [53]:
data[["Vermont", "Nevada", "Idaho"]] = np.nan
data
data.groupby(group_key).size()
data.groupby(group_key).count()
data.groupby(group_key).mean()

In [54]:
def fill_mean(group):
    return group.fillna(group.mean())

data.groupby(group_key).apply(fill_mean)

In [55]:
fill_values = {"East": 0.5, "West": -1}
def fill_func(group):
    return group.fillna(fill_values[group.name])

data.groupby(group_key).apply(fill_func)

In [56]:
suits = ["H", "S", "C", "D"]  # Hearts, Spades, Clubs, Diamonds
card_val = (list(range(1, 11)) + [10] * 3) * 4
base_names = ["A"] + list(range(2, 11)) + ["J", "K", "Q"]
cards = []
for suit in suits:
    cards.extend(str(num) + suit for num in base_names)

deck = pd.Series(card_val, index=cards)

In [57]:
deck.head(13)

In [58]:
def draw(deck, n=5):
    return deck.sample(n)
draw(deck)

In [59]:
def get_suit(card):
    # last letter is suit
    return card[-1]

deck.groupby(get_suit).apply(draw, n=2)

In [60]:
deck.groupby(get_suit, group_keys=False).apply(draw, n=2)

In [61]:
df = pd.DataFrame({"category": ["a", "a", "a", "a",
                                "b", "b", "b", "b"],
                   "data": np.random.standard_normal(8),
                   "weights": np.random.uniform(size=8)})
df

In [62]:
grouped = df.groupby("category")
def get_wavg(group):
    return np.average(group["data"], weights=group["weights"])

grouped.apply(get_wavg)

In [63]:
close_px = pd.read_csv("examples/stock_px.csv", parse_dates=True,
                       index_col=0)
close_px.info()
close_px.tail(4)

In [64]:
def spx_corr(group):
    return group.corrwith(group["SPX"])

In [65]:
rets = close_px.pct_change().dropna()

In [66]:
def get_year(x):
    return x.year

by_year = rets.groupby(get_year)
by_year.apply(spx_corr)

In [67]:
def corr_aapl_msft(group):
    return group["AAPL"].corr(group["MSFT"])
by_year.apply(corr_aapl_msft)

In [68]:
import statsmodels.api as sm
def regress(data, yvar=None, xvars=None):
    Y = data[yvar]
    X = data[xvars]
    X["intercept"] = 1.
    result = sm.OLS(Y, X).fit()
    return result.params

In [69]:
by_year.apply(regress, yvar="AAPL", xvars=["SPX"])

In [70]:
df = pd.DataFrame({'key': ['a', 'b', 'c'] * 4,
                   'value': np.arange(12.)})
df

In [71]:
g = df.groupby('key')['value']
g.mean()

In [72]:
def get_mean(group):
    return group.mean()
g.transform(get_mean)

In [73]:
g.transform('mean')

In [74]:
def times_two(group):
    return group * 2
g.transform(times_two)

In [75]:
def get_ranks(group):
    return group.rank(ascending=False)
g.transform(get_ranks)

In [76]:
def normalize(x):
    return (x - x.mean()) / x.std()

In [77]:
g.transform(normalize)
g.apply(normalize)

In [78]:
g.transform('mean')
normalized = (df['value'] - g.transform('mean')) / g.transform('std')
normalized

In [79]:
tips.head()
tips.pivot_table(index=["day", "smoker"],
                 values=["size", "tip", "tip_pct", "total_bill"])

In [80]:
tips.pivot_table(index=["time", "day"], columns="smoker",
                 values=["tip_pct", "size"])

In [81]:
tips.pivot_table(index=["time", "day"], columns="smoker",
                 values=["tip_pct", "size"], margins=True)

In [82]:
tips.pivot_table(index=["time", "smoker"], columns="day",
                 values="tip_pct", aggfunc=len, margins=True)

In [83]:
tips.pivot_table(index=["time", "size", "smoker"], columns="day",
                 values="tip_pct", fill_value=0)

In [84]:
from io import StringIO
data = """Sample  Nationality  Handedness
1   USA  Right-handed
2   Japan    Left-handed
3   USA  Right-handed
4   Japan    Right-handed
5   Japan    Left-handed
6   Japan    Right-handed
7   USA  Right-handed
8   USA  Left-handed
9   Japan    Right-handed
10  USA  Right-handed"""
data = pd.read_table(StringIO(data), sep="\s+")

In [85]:
data

In [86]:
pd.crosstab(data["Nationality"], data["Handedness"], margins=True)

In [87]:
pd.crosstab([tips["time"], tips["day"]], tips["smoker"], margins=True)

In [89]:
pd.options.display.max_rows = PREVIOUS_MAX_ROWS