In [1]:
import numpy as np
import pandas as pd
import re
from pandas import Series, DataFrame

In [24]:
data = pd.Series(np.random.uniform(size=9),
                 index=[['a','a','a','b','b','c','c','d','d'],
                        [1,2,3,1,3,1,2,2,3]])
data
data['b']
data['b':'c']
data.loc[['b','d']]
data.loc[:,2]
data.unstack()
data.unstack().stack()

frame = pd.DataFrame(np.arange(12).reshape((4,3)),
                     index=[['a','a','b','b'],[1,2,1,2]],
                     columns=[['Ohio','Ohio','Colorado'],['Green','Red','Green']])
frame
frame.index.names = ['key1','key2']
frame.columns.names = ['state','color']

frame.index.nlevels
frame['Ohio']
pd.MultiIndex.from_arrays([['Ohio','Ohio','Colorado'],['Green','Red','Green']], names=['state','color'])
frame.swaplevel('key1','key2')
frame.sort_index(level=1)
frame.swaplevel(0,1).sort_index(level=0)
print(frame)
print(frame.groupby(level='key2').sum())
print(frame.T.groupby(level='color').sum().T)

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11
state  Ohio     Colorado
color Green Red    Green
key2
1         6   8       10
2        12  14       16
color      Green  Red
key1 key2
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

In [29]:
frame = pd.DataFrame({'a':range(7),'b':range(7,0,-1),
                      'c':['one','one','one','two','two','two','two'],
                      'd':[0,1,2,0,1,2,3]})
frame
frame2 = frame.set_index(['c','d'])
frame2
frame.set_index(['c','d'],drop=False)

       a  b    c  d
c   d
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

In [ ]:
df1 = pd.DataFrame({'key':['b','b','a','c','a','a','b'],
                    'data1':pd.Series(range(7), dtype='int64')})
df2 = pd.DataFrame({'key':['a','b','d'],
                    'data2': pd.Series(range(3), dtype = 'int64')})
print(df1)
print(df2)
pd.merge(df1,df2)
pd.merge(df1,df2, on='key')

df3 = pd.DataFrame({'lkey':['b','b','a','c','a','a','b'],
                    'data1': pd.Series(range(7), dtype='Int64')})
df4 = pd.DataFrame({'rkey':['a','b','d'],
                    'data2': pd.Series(range(3), dtype='Int64')})
pd.merge(df3, df4, left_on='lkey',right_on='rkey')
pd.merge(df1, df2, how='outer')
pd.merge(df3,df4,left_on='lkey',right_on='rkey',how='outer')

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6
  key  data2
0   a      0
1   b      1
2   d      2

  lkey  data1 rkey  data2
0    a      2    a      0
1    a      4    a      0
2    a      5    a      0
3    b      0    b      1
4    b      1    b      1
5    b      6    b      1
6    c      3  NaN   <NA>
7  NaN   <NA>    d      2

In [ ]:
df1 = pd.DataFrame({'key':['b','b','a','c','a','b'],
                    'data1': pd.Series(range(6),dtype='Int64')})
df2 = pd.DataFrame({'key':['a','b','a','b','d'],
                    'data2': pd.Series(range(5),dtype='Int64')})
print(df1)
print(df2)
pd.merge(df1, df2, on='key',how='left')
pd.merge(df1,df2,how="inner")

left = pd.DataFrame({'key1':['foo','foo','bar'],
                     'key2':['one','two','one'],
                     'lval':pd.Series([1,2,3], dtype='Int64')})
right = pd.DataFrame({'key1':['foo','foo','bar','bar'],
                     'key2':['one','one','one','two'],
                     'rval':pd.Series([4,5,6,7], dtype='Int64')})
pd.merge(left,right,on=['key1','key2'],how='outer')

pd.merge(left,right,on='key1',suffixes=('_left','_right'))

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5
  key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

  key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

In [16]:
left1 = pd.DataFrame({'key':['a','b','a','a','b','c'],
                      'value':range(6)})
right1 = pd.DataFrame({'group_val':[3.5,7]}, index=['a','b'])
print(left1)
print(right1)
pd.merge(left1,right1,left_on='key',right_index=True)
pd.merge(left1,right1,left_on='key',right_index=True,how='outer')

  key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5
   group_val
a        3.5
b        7.0

  key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [22]:
lefth = pd.DataFrame({'key1':['Ohio','Ohio','Ohio','Nevada','Nevada'],
                      'key2':[2000,2001,2002,2001,2002],
                      'data':pd.Series(range(5),dtype='Int64')})
righth_index = pd.MultiIndex.from_arrays(
    [
        ['Nevada','Nevada','Ohio','Ohio','Ohio','Ohio'],
        [2001,2000,2000,2000,2001,2002]
    ]
)
righth=pd.DataFrame({'event1':pd.Series([0,2,4,6,8,10],dtype='Int64',index=righth_index),
                     'event2':pd.Series([1,3,5,7,9,11],dtype='Int64',index=righth_index)})

print(lefth)
pd.merge(lefth, righth,left_on=['key1','key2'],right_index=True)
pd.merge(lefth,righth,left_on=['key1','key2'], right_index=True,how='outer')

     key1  key2  data
0    Ohio  2000     0
1    Ohio  2001     1
2    Ohio  2002     2
3  Nevada  2001     3
4  Nevada  2002     4

     key1  key2  data  event1  event2
4  Nevada  2000  <NA>       2       3
3  Nevada  2001     3       0       1
4  Nevada  2002     4    <NA>    <NA>
0    Ohio  2000     0       4       5
0    Ohio  2000     0       6       7
1    Ohio  2001     1       8       9
2    Ohio  2002     2      10      11